
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
EMACS=emacs
EMACSCLIENT=emacsclient
export VISUAL="$EMACSCLIENT -t"
export EDITOR="$VISUAL"
alias em="$EMACSCLIENT -c -a $EMACS"
alias ec="$EMACSCLIENT -c"
# IPython debugger in pytest
alias pytestdb='pytest --pdb --pdbcls=IPython.terminal.debugger:TerminalPdb --capture no'
# Make sure pytest adds current directory to sys.path
alias pytest='python -m pytest'
alias _pytest='command pytest'

# alias for managing dotfiles with stow
DOTFILES_DIR=~/dev/dotfiles
alias dotfiles-stow="stow --target ~ --dir $DOTFILES_DIR -S ."
alias dotfiles-restow="dotfiles-stow -R"
# useful to run dotfiles st from any folder
alias dotfiles="git -C $DOTFILES_DIR"

# bat is called batcat on Ubuntu
alias bat=batcat
# Taken from https://remysharp.com/2018/08/23/cli-improved
alias preview="fzf --preview 'batcat --color \"always\" {}'"

# terminal 256 color support
if [[ "$TERM" == "xterm" ]]; then
    export TERM="xterm-256color"
fi
if [[ "$TERM" == "screen" ]]; then
    export TERM="screen-256color"
fi

# Magically link PYTHONPATH to the ZSH array pythonpath
typeset -T PYTHONPATH pythonpath
# Remove duplicates
typeset -U pythonpath path
export PYTHONPATH pythonpath

# Alias to have help for bash builtins
function help() {
    bash --norc -c "help $1"
}

# Aliases for switching conda environments
alias ca='cda && conda activate'
alias cda='conda deactivate'

# Prepending custom paths
# join function from http://stackoverflow.com/a/17841619
function join_by { local IFS="$1"; shift; echo "$*"; }

CCACHE_PATH=/usr/lib/ccache
MY_BIN_PATH="$HOME/bin"

PATHS_TO_PREPEND=$(join_by ':' $CCACHE_PATH $MY_BIN_PATH)

if [ -n "$PATHS_TO_PREPEND" ]; then
    export PATH="$PATHS_TO_PREPEND:$PATH"
fi

SHELL_TOOLS_ENV="$MINICONDA_PATH/envs/shell-tools"
SHELL_TOOLS_PATH="$SHELL_TOOLS_ENV/bin"

PATHS_TO_APPEND=$(join_by ':' $SHELL_TOOLS_PATH)

if [ -n "$PATHS_TO_APPEND" ]; then
    export PATH="$PATH:$PATHS_TO_APPEND"
fi

# Switches the mouse handedness using the command line rather than
# going via system setting
function mouse-switch() {
    handedness=$1
    shift
    case $handedness in
        left|l)
            xmodmap -e 'pointer = 3 2 1'
            return $?
            ;;
        right|r)
            xmodmap -e 'pointer = 1 2 3'
            return $?
            ;;
        *)
            echo "Argument should be one of 'left, l, right, l'"
            return 1
            ;;
    esac
}

# Make * match files starting with .
setopt globdots

# Set up fzf completions and shortcuts
FZF_SHARE=$SHELL_TOOLS_ENV/share/fzf
if [[ -d $FZF_SHARE ]]; then
    source $FZF_SHARE/shell/completion.zsh
    source $FZF_SHARE/shell/key-bindings.zsh
fi

# Easy way to have pass ** use fzf for password completion
_fzf_complete_pass() {
  ARGS="$@"
  _fzf_complete '' "$@" < <(
    command find ~/.password-store/ -name "*.gpg" | sed -r 's,(.*)\.password-store/(.*)\.gpg,\2,'
  )
}

# Need this to make sure module command available
# on some HPC clusters
if [[ -d $MODULESHOME ]]; then
    source $MODULESHOME/init/zsh
fi
