#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
EMACS=emacs
EMACSCLIENT="${EMACS}client"
export VISUAL="$EMACSCLIENT -t"
export EDITOR="$VISUAL"
alias em="$EMACSCLIENT -c -a $EMACS"
alias ec="$EMACSCLIENT -c"

# Magically link PYTHONPATH to the ZSH array pythonpath
typeset -T PYTHONPATH pythonpath
# Remove duplicates
typeset -U pythonpath path
export PYTHONPATH pythonpath

# Alias to have help for bash builtins
function help() {
    bash --norc -c "help $1"
}

# Alias to use IPython debugger with py.test
alias pytestdb='pytest --pdb --pdbcls=IPython.terminal.debugger:TerminalPdb --capture no'

# Aliases for switching conda environments
alias ca='. activate'
alias cda='. deactivate'

# Prepending custom paths
# join function from http://stackoverflow.com/a/17841619
function join_by { local IFS="$1"; shift; echo "$*"; }

ANACONDA_PATH="$HOME/miniconda3/bin"
CCACHE_PATH=/usr/lib/ccache
MY_BIN_PATH="$HOME/bin"
PATHS_TO_PREPEND=$(join_by ':' $ANACONDA_PATH $CCACHE_PATH $MY_BIN_PATH)

if [ -n "$PATHS_TO_PREPEND" ]; then
    export PATH="$PATHS_TO_PREPEND:$PATH"
fi

# Switches the mouse handedness using the command line rather than
# going via system setting
function mouse-switch() {
    handedness=$1
    shift
    case $handedness in
        left|l)
            xmodmap -e 'pointer = 3 2 1'
            return $?
            ;;
        right|r)
            xmodmap -e 'pointer = 1 2 3'
            return $?
            ;;
        *)
            echo "Argument should be one of 'left, l, right, l'"
            return 1
            ;;
    esac
}
